# Generated by Django 3.2.7 on 2021-11-22 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='leave',
            name='leave_type',
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='human_resource.leavetype'),
        ),
    ]
